Repository Salentech/exercise-db-connection, pull requests merged in 2024-12, with the labels that each got.

#13 pagination implementation
  Controllers/HomeController.cs
  Repositories/BookRepository.cs
  Views/Home/Index.cshtml
Labels: enhancement

#17 added back button and changed style
  Controllers/HomeController.cs
  Controllers/ReviewController.cs
  Data/AppContext.cs
  Data/AppDbContextFactory.cs
  Migrations/20241126182109_InitialCreate.Designer.cs
  Migrations/AppDbContextModelSnapshot.cs
  Models/Book.cs
  Models/Review.cs
  Program.cs
  Repositories/BookRepository.cs
  Repositories/ReviewRepository.cs
  Views/Home/Index.cshtml
  Views/Review/Reviews.cshtml
  Views/Shared/_Layout.cshtml
  exercise-db-connection.csproj
  wwwroot/Images/logo.svg
  wwwroot/css/site.css
  wwwroot/lib/bootstrap/dist/js/bootstrap.bundle.js
  wwwroot/lib/bootstrap/dist/js/bootstrap.esm.js
  wwwroot/lib/bootstrap/dist/js/bootstrap.js
Labels: enhancement

#18 tests implementation
  Test/example-db-connection-test/Repositories/BookRepositoryTests.cs
  Test/example-db-connection-test/Repositories/ReviewRepositoryTests.cs
  exercise-db-connection.csproj
Labels: enhancement

#19 fixed missing imports
  Test/example-db-connection-test/Repositories/BookRepositoryTests.cs
  Test/example-db-connection-test/Repositories/ReviewRepositoryTests.cs
  exercise-db-connection.csproj
  wwwroot/Images/logo.svg
Labels: bug

#22 Add authentication
  Program.cs
  Views/Shared/_Layout.cshtml
  appsettings.json
  exercise-db-connection.csproj
Labels: enhancement

#26 added working next and previous buttons on review list
  Controllers/ReviewController.cs
  Repositories/ReviewRepository.cs
  Test/example-db-connection-test/Repositories/ReviewRepositoryTests.cs
  Views/Review/Reviews.cshtml
Labels: enhancement

#27 23-add-sign-in-and-sign-out-buttons
  Program.cs
  Views/Shared/_Layout.cshtml
  Views/Shared/_Layout.cshtml.css
  exercise-db-connection.csproj
  wwwroot/css/site.css
  wwwroot/images/logo.svg
Labels: bug, enhancement
